apiVersion: v1
kind: ServiceAccount
metadata:
  name: binpack-scheduler
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: binpack-scheduler-clusterrolebinding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: binpack-scheduler
    namespace: kube-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: kube-system
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
      - schedulerName: binpack-scheduler
        plugins:
          filter:
            enabled:
              - name: Priority
          score:
            enabled:
              - name: Priority
            disabled:
              - name: "*"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: binpack-scheduler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      component: binpack-scheduler
  template:
    metadata:
      labels:
        component: binpack-scheduler
    spec:
      serviceAccount: binpack-scheduler
      priorityClassName: system-cluster-critical
      volumes:
        - name: scheduler-config
          configMap:
            name: scheduler-config
      containers:
        - name: binpack-scheduler
          image: 192.168.110.64:5000/kube-scheduler:binpack
          args:
            - --config=/etc/kubernetes/scheduler-config.yaml
            - --v=3
          volumeMounts:
            - name: scheduler-config
              mountPath: /etc/kubernetes
